<a href="https://colab.research.google.com/github/datasci888/AttentionDetection/blob/main/Dataset_II_Part_III_Attention_Per_User_LeaveOneOut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# path of csv files
# directory = r"/content/drive/MyDrive/"

In [ ]:
# directory2 = r"/content/drive/MyDrive/NewCVStoPart-IIIMarch1/"

In [ ]:
# array2 = []
# for file in os.listdir(directory2):
#     print(file)
#     filepath = os.path.join(directory2,file)
#     df_temp = pd.read_csv(filepath)
#     df_temp['Channel'] = file.split('.')[0]
#     array2.append(df_temp)

In [ ]:

dfTrain = pd.read_csv(r'/content/drive/MyDrive/NewCVStoPart-IIIMarch1/NewCSVMarch1_Dataset_II_BandstoPart-IIITrain.csv')

In [ ]:
dfTest = pd.read_csv(r'/content/drive/MyDrive/NewCVStoPart-IIIMarch1/NewCSVMarch1_Dataset_II_BandstoPart-IIITest.csv')
# vertical_concat2.to_csv('/content/drive/MyDrive/NewCVStoPart-IIIMarch1/NewCSVMarch1_Dataset_II_BandstoPart-IIITest.csv', index = False)

In [ ]:
# df = pd.concat(array2)
# len(df)

In [ ]:
dfTrain.head()


Alpha       Delta       Beta     Gamma  Label
0  21.582478   75.814406   9.235991  0.708799  Focus
1   1.173516    5.487767   1.075237  0.142068  Focus
2   1.795885   31.367239   0.837457  0.117887  Focus
3  18.083213   52.505458   7.819185  0.777453  Focus
4  44.822451  191.980194  17.116479  1.270734  Focus

In [ ]:
dfTest.head()

Alpha       Delta       Beta     Gamma  Label
0  21.582478   75.814406   9.235991  0.708799  Focus
1   1.173516    5.487767   1.075237  0.142068  Focus
2   1.795885   31.367239   0.837457  0.117887  Focus
3  18.083213   52.505458   7.819185  0.777453  Focus
4  44.822451  191.980194  17.116479  1.270734  Focus

In [ ]:
# duplicate = df[df.duplicated()]
 
# print("Duplicate Rows :", duplicate)
# duplicate

In [ ]:
# df= df.drop(columns = ['Channel'], axis =1)

In [ ]:
# df

In [ ]:
# shuffle the DataFrame rows
# df = df.sample(frac = 1)
# df.head()

In [ ]:
#import label encoder
from sklearn import preprocessing 
#make an instance of Label Encoder
label_encoder = preprocessing.LabelEncoder()
y_train = label_encoder.fit_transform(dfTrain['Label'])
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
#import label encoder
from sklearn import preprocessing 
#make an instance of Label Encoder
label_encoder = preprocessing.LabelEncoder()
y_test = label_encoder.fit_transform(dfTest['Label'])
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
X_train = dfTrain.drop('Label',axis=1)
X_test = dfTest.drop('Label',axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, shuffle = True, random_state = 40, stratify = y)
# stratify = y makes sure that the rtatio of output columns are same in train and test

<!-- K-Fold - run 10 times and get average -->

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[ 1.84783894,  1.46527842,  2.05763656,  1.93297109],
       [-0.43618662, -0.40013887, -0.22067873, -0.15100379],
       [-0.36653549,  0.2863153 , -0.28706204, -0.23992317],
       [ 1.45622621,  0.84700751,  1.66209324,  2.18542435],
       [ 4.44869116,  4.54658118,  4.25770732,  3.99931099],
       [-0.40306549, -0.32275105, -0.01410656,  0.02761433],
       [-0.14603428, -0.13199769,  0.06293757,  0.30568365],
       [ 1.84783894,  1.46527842,  2.05763656,  1.93297109],
       [-0.43618662, -0.40013887, -0.22067873, -0.15100379],
       [-0.36653549,  0.2863153 , -0.28706204, -0.23992317],
       [ 1.45622621,  0.84700751,  1.66209324,  2.18542435],
       [ 4.44869116,  4.54658118,  4.25770732,  3.99931099],
       [-0.40306549, -0.32275105, -0.01410656,  0.02761433],
       [-0.14603428, -0.13199769,  0.06293757,  0.30568365],
       [-0.42055511, -0.51141499, -0.38627883, -0.42220556],
       [-0.35034469, -0.46071874, -0.33818968, -0.35337933],
       [-0.18981856, -0.

In [ ]:
len(y_train)

56

# DecisionTreeClassifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
dt_acc = accuracy_score(y_test,y_pred)
print(classification_report(y_test,y_pred))
print('Accuracy ', np.round(dt_acc,2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      1.00      1.00        21

    accuracy                           1.00        42
   macro avg       1.00      1.00      1.00        42
weighted avg       1.00      1.00      1.00        42

Accuracy  1.0


In [ ]:
# # DT New
# from sklearn.tree import DecisionTreeClassifier
# classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 42)
# classifier.fit(X_train, y_train)
# y_pred = classifier.predict(X_trainNew)
# dt_acc = accuracy_score(Y_testNew,y_pred)
# print(classification_report(Y_testNew,y_pred))
# print('Accuracy ', np.round(dt_acc,2))

In [ ]:
# pip install scikit

##LightBGM

In [ ]:
from lightgbm import LGBMClassifier
classifier = LGBMClassifier(random_state=5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
lightgbm_acc = accuracy_score(y_test,y_pred)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.86      0.82        21
           1       0.84      0.76      0.80        21

    accuracy                           0.81        42
   macro avg       0.81      0.81      0.81        42
weighted avg       0.81      0.81      0.81        42



In [ ]:
# from sklearn.metrics import plot_confusion_matrix
# plot_confusion_matrix(classifier, X_test, y_test)  
# plt.show()

## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
lg_acc = accuracy_score(y_test,y_pred)
print('Accuracy ', np.round(lg_acc,2))
print(classification_report(y_test,y_pred))

Accuracy  0.79
              precision    recall  f1-score   support

           0       1.00      0.57      0.73        21
           1       0.70      1.00      0.82        21

    accuracy                           0.79        42
   macro avg       0.85      0.79      0.78        42
weighted avg       0.85      0.79      0.78        42



In [ ]:
y_pred = classifier.predict_proba(X_test)


In [ ]:
y_pred
# 0.49727592% chNCW FOCUSED

array([[0.96928132, 0.03071868],
       [0.54078192, 0.45921808],
       [0.41455677, 0.58544323],
       [0.97629574, 0.02370426],
       [0.99749282, 0.00250718],
       [0.63207625, 0.36792375],
       [0.68573132, 0.31426868],
       [0.96928132, 0.03071868],
       [0.54078192, 0.45921808],
       [0.41455677, 0.58544323],
       [0.97629574, 0.02370426],
       [0.99749282, 0.00250718],
       [0.63207625, 0.36792375],
       [0.68573132, 0.31426868],
       [0.43172893, 0.56827107],
       [0.45303834, 0.54696166],
       [0.4308406 , 0.5691594 ],
       [0.46627044, 0.53372956],
       [0.43449247, 0.56550753],
       [0.47654353, 0.52345647],
       [0.41776372, 0.58223628],
       [0.37604324, 0.62395676],
       [0.38393478, 0.61606522],
       [0.41136552, 0.58863448],
       [0.4080636 , 0.5919364 ],
       [0.4018691 , 0.5981309 ],
       [0.44177338, 0.55822662],
       [0.40373715, 0.59626285],
       [0.36948711, 0.63051289],
       [0.42502141, 0.57497859],
       [0.

In [ ]:
# from sklearn.metrics import plot_confusion_matrix
# plot_confusion_matrix(classifier, X_test, y_test)  
# plt.show()

In [ ]:
# print(confusion_matrix(y_test,y_pred))

In [ ]:
# from sklearn.metrics import plot_confusion_matrix
# plot_confusion_matrix(classifier, X_test, y_test)  
# plt.show()

## KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
import math
k=math.sqrt(60)
classifier = KNeighborsClassifier(n_neighbors=8)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
knn_acc = accuracy_score(y_test,y_pred)
print('Accuracy ', np.round(knn_acc,2))
print(classification_report(y_test,y_pred))

Accuracy  0.74
              precision    recall  f1-score   support

           0       0.73      0.76      0.74        21
           1       0.75      0.71      0.73        21

    accuracy                           0.74        42
   macro avg       0.74      0.74      0.74        42
weighted avg       0.74      0.74      0.74        42



In [ ]:
# To get probability:
y_pred = classifier.predict_proba(X_test)
# knn_acc = accuracy_score(y_test,y_pred)
# print('Accuracy ', np.round(knn_acc,2))
# print(classification_report(y_test,y_pred))

In [ ]:
y_pred

array([[0.875, 0.125],
       [0.625, 0.375],
       [0.25 , 0.75 ],
       [1.   , 0.   ],
       [0.875, 0.125],
       [1.   , 0.   ],
       [0.875, 0.125],
       [0.875, 0.125],
       [0.625, 0.375],
       [0.25 , 0.75 ],
       [1.   , 0.   ],
       [0.875, 0.125],
       [1.   , 0.   ],
       [0.875, 0.125],
       [0.75 , 0.25 ],
       [0.625, 0.375],
       [0.25 , 0.75 ],
       [0.5  , 0.5  ],
       [0.375, 0.625],
       [0.375, 0.625],
       [0.5  , 0.5  ],
       [0.375, 0.625],
       [0.5  , 0.5  ],
       [0.375, 0.625],
       [0.125, 0.875],
       [0.25 , 0.75 ],
       [0.   , 1.   ],
       [0.625, 0.375],
       [0.25 , 0.75 ],
       [0.25 , 0.75 ],
       [0.375, 0.625],
       [0.25 , 0.75 ],
       [0.25 , 0.75 ],
       [0.25 , 0.75 ],
       [0.375, 0.625],
       [0.625, 0.375],
       [0.375, 0.625],
       [0.625, 0.375],
       [0.375, 0.625],
       [0.25 , 0.75 ],
       [0.5  , 0.5  ],
       [0.5  , 0.5  ]])

In [ ]:
# print(confusion_matrix(y_test,y_pred))
# from sklearn.metrics import plot_confusion_matrix
# plot_confusion_matrix(classifier, X_test, y_test)  
# plt.show()

##NaiveBayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
NB_acc = accuracy_score(y_test,y_pred)
print('Accuracy ', np.round(NB_acc,2))
print(classification_report(y_test,y_pred))

Accuracy  0.74
              precision    recall  f1-score   support

           0       1.00      0.48      0.65        21
           1       0.66      1.00      0.79        21

    accuracy                           0.74        42
   macro avg       0.83      0.74      0.72        42
weighted avg       0.83      0.74      0.72        42



In [ ]:
# print(confusion_matrix(y_test,y_pred))
# from sklearn.metrics import plot_confusion_matrix
# plot_confusion_matrix(classifier, X_test, y_test)  
# plt.show()

## ADABoost

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
classifier = AdaBoostClassifier(n_estimators=100, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
ada_acc = accuracy_score(y_test,y_pred)
print('Accuracy ', np.round(ada_acc,2))
print(classification_report(y_test,y_pred))

Accuracy  1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      1.00      1.00        21

    accuracy                           1.00        42
   macro avg       1.00      1.00      1.00        42
weighted avg       1.00      1.00      1.00        42



In [ ]:
# print(confusion_matrix(y_test,y_pred))
# from sklearn.metrics import plot_confusion_matrix
# plot_confusion_matrix(classifier, X_test, y_test)  
# plt.show()

##Bagging

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
classifier = BaggingClassifier(base_estimator=SVC(),n_estimators=10, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
bg_acc = accuracy_score(y_test,y_pred)
print('Accuracy ', np.round(bg_acc,2))
print(classification_report(y_test,y_pred))

Accuracy  0.69
              precision    recall  f1-score   support

           0       1.00      0.38      0.55        21
           1       0.62      1.00      0.76        21

    accuracy                           0.69        42
   macro avg       0.81      0.69      0.66        42
weighted avg       0.81      0.69      0.66        42



/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


In [ ]:
# print(confusion_matrix(y_test,y_pred))
# from sklearn.metrics import plot_confusion_matrix
# plot_confusion_matrix(classifier, X_test, y_test)  
# plt.show()

##LDA

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
classifier = LinearDiscriminantAnalysis()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
lda_acc = accuracy_score(y_test,y_pred)
print('Accuracy ', np.round(lda_acc,2))
print(classification_report(y_test,y_pred))

Accuracy  0.81
              precision    recall  f1-score   support

           0       1.00      0.62      0.76        21
           1       0.72      1.00      0.84        21

    accuracy                           0.81        42
   macro avg       0.86      0.81      0.80        42
weighted avg       0.86      0.81      0.80        42



In [ ]:
# print(confusion_matrix(y_test,y_pred))
# from sklearn.metrics import plot_confusion_matrix
# plot_confusion_matrix(classifier, X_test, y_test)  
# plt.show()

# RandomForest



In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
rf_acc = accuracy_score(y_test,y_pred)
print('Accuracy ', np.round(rf_acc,2))
print(classification_report(y_test,y_pred))

Accuracy  1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      1.00      1.00        21

    accuracy                           1.00        42
   macro avg       1.00      1.00      1.00        42
weighted avg       1.00      1.00      1.00        42



In [ ]:
# print(confusion_matrix(y_test,y_pred))
# from sklearn.metrics import plot_confusion_matrix
# plot_confusion_matrix(classifier, X_test, y_test)  
# plt.show()

# XGBClassifier

In [ ]:
from xgboost import XGBClassifier

In [ ]:
# #import label encoder
# from sklearn import preprocessing 
# #make an instance of Label Encoder
# label_encoder = preprocessing.LabelEncoder()
# y_train = label_encoder.fit_transform(y_train)
# y_train

In [ ]:
# #import label encoder
# from sklearn import preprocessing 
# #make an instance of Label Encoder
# label_encoder = preprocessing.LabelEncoder()
# y_test = label_encoder.fit_transform(y_test)
# y_test

In [ ]:

#import label encoder
from sklearn import preprocessing 
#make an instance of Label Encoder
label_encoder = preprocessing.LabelEncoder()
y_pred = label_encoder.fit_transform(y_pred)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
xgb = XGBClassifier(n_estimators=100,random_state = 42)
xgb.fit(X_train, y_train)
preds = xgb.predict(X_test)
xbg_acc = accuracy_score(y_test,preds)

In [ ]:
print(classification_report(y_test,preds))
print('Accuracy ', np.round(xbg_acc,2))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      1.00      1.00        21

    accuracy                           1.00        42
   macro avg       1.00      1.00      1.00        42
weighted avg       1.00      1.00      1.00        42

Accuracy  1.0


In [ ]:
# print(confusion_matrix(y_test,preds))
# from sklearn.metrics import plot_confusion_matrix
# plot_confusion_matrix(xgb, X_test, y_test)  
# plt.show()

# MLP

In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
clf = MLPClassifier(hidden_layer_sizes=(100,),random_state=42)
clf.fit(X_train, y_train)
y_pred_mlp = clf.predict(X_test)
mlp_acc = accuracy_score(y_test,y_pred_mlp)
print('Accuracy ', np.round(mlp_acc,2))


Accuracy  0.86


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:684: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
print(classification_report(y_test,y_pred_mlp))

              precision    recall  f1-score   support

           0       1.00      0.71      0.83        21
           1       0.78      1.00      0.88        21

    accuracy                           0.86        42
   macro avg       0.89      0.86      0.85        42
weighted avg       0.89      0.86      0.85        42



# SVM

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc = SVC(random_state = 42)
svc.fit(X_train, y_train)
preds = svc.predict(X_test)
svc_acc = accuracy_score(y_test,preds)
print('Accuracy ', np.round(svc_acc,2))
print(classification_report(y_test,preds))

Accuracy  0.69
              precision    recall  f1-score   support

           0       1.00      0.38      0.55        21
           1       0.62      1.00      0.76        21

    accuracy                           0.69        42
   macro avg       0.81      0.69      0.66        42
weighted avg       0.81      0.69      0.66        42





```
# This is formatted as code
```

### Random Forest Tuning

In [ ]:
# from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
# from sklearn.ensemble import RandomForestClassifier
# param_grid = {'max_features': ['auto', 'sqrt', 'log2'],
#               'ccp_alpha': [0.1, .01, .001],
#               'max_depth' : [3, 5, 6, 7, 8, 9],
#               'criterion' :['gini', 'entropy']
#              }

# gs2 = GridSearchCV(RandomForestClassifier(random_state = 42), param_grid, n_jobs=-1, 
#                    cv=10, scoring='accuracy',verbose=3)
# gs2.fit(X_train, y_train)

In [ ]:
# rf_tuned = gs2.best_estimator_
# rf_tuned.fit(X_train, y_train)
# y_pred_rf = rf_tuned.predict(X_test)
# rf_acc_tuned = accuracy_score(y_test,y_pred_rf)
# print(classification_report(y_test,y_pred_rf))

### DT Tuning

In [ ]:
# param_grid = {'max_features': ['auto', 'sqrt', 'log2'],
#               'ccp_alpha': [0.1, .01, .001],
#               'max_depth' : [5, 6, 7, 8, 9],
#               'criterion' :['gini', 'entropy']
#              }

# gs2 = GridSearchCV(DecisionTreeClassifier(random_state = 42), param_grid, n_jobs=-1, 
#                    cv=3, scoring='accuracy',verbose=3)
# gs2.fit(X_train, y_train)

In [ ]:
# dt_tuned = gs2.best_estimator_
# dt_tuned.fit(X_train, y_train)
# y_pred_dt = dt_tuned.predict(X_test)
# dt_acc_tuned = accuracy_score(y_test,y_pred_dt)
# print(classification_report(y_test,y_pred_dt))

# performance comparison

In [ ]:

results = pd.DataFrame({
    'Model After PerUser classification Leave one out': ['KNN',
              'NB',
              'Decision Tree',
              'Random Forest', 
              'XGBoost', 
              'ADABoost',
              'Bagging',
              'LDA',
              'MLPClassifier',
              'Logistic Regression',
              'SVC',
              'LightBGM'],
    'Score': [ knn_acc,
                NB_acc,
                dt_acc,
                rf_acc,
                xbg_acc,
                ada_acc,
                bg_acc,
                lda_acc,
                mlp_acc,
              lightgbm_acc,
                lg_acc,
                svc_acc]
                })
results['Score'] = results['Score'].apply(lambda x: np.round(x,2))
result_df = results.sort_values(by='Score', ascending=False)
result_df = result_df.set_index('Model After PerUser classification Leave one out')
result_df

Score
Model After PerUser classification Leave one out       
Decision Tree                                      1.00
Random Forest                                      1.00
XGBoost                                            1.00
ADABoost                                           1.00
MLPClassifier                                      0.86
LDA                                                0.81
Logistic Regression                                0.81
SVC                                                0.79
KNN                                                0.74
NB                                                 0.74
Bagging                                            0.69
LightBGM                                           0.69